In [1]:
import torch
from torch import tensor


In [11]:
x = tensor(42.)
print(x)

tensor(42.)


In [12]:
x.dim()

0

In [13]:
2 * x

tensor(84.)

In [6]:
x.item()

42.0

In [7]:
v = tensor([1.5, -0.5, 3.0])

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [14]:
v.size()

torch.Size([3])

torch.Size([3])

In [17]:
M = tensor([[1, 2], [3, 4]])
M

tensor([[1, 2],
        [3, 4]])

In [18]:
M.matmul(M)

tensor([[ 7, 10],
        [15, 22]])

In [19]:
tensor([1, 0]).matmul(M)

tensor([1, 2])

In [20]:
M * M

tensor([[ 1,  4],
        [ 9, 16]])